### ISSUE TITLE
Control via Wi-Fi

### ISSUE THREAD

**Issue by BlackWarriorNT** [ccourson/LewanSoul-xArm#2]
Good day!
I am disabled since birth and it is very difficult for me to perform any physical actions with most objects. One good person gave me xArm (6DOF Arm Robot) from LewanSoul.
This manipulator suits me everything except control software. Could you try to adapt your project for the xArm + ESP8266 bundle?

**Comment by ccourson** [comment]
That's a great idea. I will look into it.

**Comment by BlackWarriorNT** [comment]
OK. How about web-interface? Can you integrate this project https://forum.phpoc.com/blogs/khanh-s-blog/1129-arduino-control-arm-robot-via-web ?

**Comment by ccourson** [comment]
I can do something similar. I am working on a library for ESP in Lua, MicroPython and Arduino presently.

**Comment by BlackWarriorNT** [comment]
ok
